export const about = {
  name: 'James Travis McHorse',
  title: 'AI/ML Engineer · Automation Architect · Full-Stack Technologist',
  location: 'Spokane, WA',
  email: 'jmchorse.tech@gmail.com',
  phone: '(206) 486-5459',
  summary:
    'Senior Full-Stack Engineer with 12+ years building scalable web apps & AI integrations. React, Node.js, Python, AWS. Cut deployment time 80%.',
  yearsOfExperience: 12,
  website: 'leftcoaststack.com',
  github: 'https://github.com/jmchorse',
  linkedin: 'https://linkedin.com/in/jmchorse',
  keyAchievements: [
    '80% reduction in deployment time via full AWS pipeline automation (Lambda, S3, App Runner, CI/CD)',
    '50% improvement in application load speed through advanced frontend optimization',
    '40% page load improvement via code splitting, lazy loading, and CDN-backed asset delivery',
    '30% DB performance gain through schema redesign and index optimization',
    '5+ zero-downtime legacy migrations from PHP/jQuery to modern React/TypeScript architecture',
    '15+ production-grade applications delivered across fintech, SaaS, government, and e-commerce',
    '20+ developers mentored — established coding standards, review processes, and architectural patterns',
  ],
  neofetchStats: {
    os: 'leftcoaststack.com v1.0.0',
    kernel: 'TypeScript 5.x',
    uptime: '12+ years',
    packages: '15+ production apps',
    shell: 'React + Next.js',
    resolution: '1440x900 (Macbook Pro)',
    de: 'Node.js + NestJS',
    wm: 'AWS (EC2, Lambda, App Runner)',
    terminal: 'VS Code + Ghostty',
    cpu: 'Brain (12-core, 3.8GHz)',
    gpu: 'React 19',
    memory: '12 Years of Experience',
  },
}
